version: "3"

services:
  webserver:
    image: 127.0.0.1:3500/webserverapp
    # build: webServerApp
    ports:
      - "5000:5000"
    restart: unless-stopped
    env_file:
      - webServerApp/web.env
    networks:
      - cat
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    
  loadbalancer:
    image: 127.0.0.1:3500/loadbalancerapp
    networks:
      - cat
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - loadBalancerApp/balancer.env
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  cat:
    name: cat
    ipam:
      driver: default

volumes:
  nfsvolume:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.56.1,nfsvers=4.1,nolock,soft,rw"
      device: ":home/huy/Videos"
    name: "nfsvolume"
  