version: "3"

services:
  videoserver1:
    image: truongvanhuy2000/videoserverapp
    # build: videoServerApp
    networks:
      - cat
    env_file:
      - video.env
    privileged: true
    volumes:
      - type: volume
        source: nfsvolume
        target: /video/
        volume:
          nocopy: true

  videoserver2:
    image: truongvanhuy2000/videoserverapp
    # build: videoServerApp
    networks:
      - cat
    env_file:
      - video.env
    privileged: true
    volumes:
      - type: volume
        source: nfsvolume
        target: /video/
        volume:
          nocopy: true

  videoserver3:
    image: truongvanhuy2000/videoserverapp
    # build: videoServerApp
    networks:
      - cat
    env_file:
      - video.env
    privileged: true
    volumes:
      - type: volume
        source: nfsvolume
        target: /video/
        volume:
          nocopy: true
        
  videoserver4:
    image: truongvanhuy2000/videoserverapp
    # build: videoServerApp
    networks:
      - cat
    env_file:
      - video.env
    privileged: true
    volumes:
      - type: volume
        source: nfsvolume
        target: /video/
        volume:
          nocopy: true

  webserver:
    image: truongvanhuy2000/webserverapp
    # build: webServerApp
    ports:
      - "8000:5000"
    restart: unless-stopped
    volumes:
      - .:/webServerApp/webServer
    env_file:
      - web.env
    networks:
      - cat
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  cat:
    name: cat
    ipam:
      driver: default

volumes:
  nfsvolume:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=$IP_ADDR,nolock,soft
      device: $MOUNT_DIR
  