version: "3"

services:
  videoserver1:
    image: truongvanhuy2000/videoserverapp
    # build: videoServerApp
    networks:
      - cat
    depends_on:
      - nfsserver
    env_file:
      - video.env
    privileged: true
    volumes:
      - "video:/video/"

  videoserver2:
    image: truongvanhuy2000/videoserverapp
    # build: videoServerApp
    networks:
      - cat
    depends_on:
      - nfsserver
    env_file:
      - video.env
    privileged: true
    volumes:
      - "video:/video/"

  videoserver3:
    image: truongvanhuy2000/videoserverapp
    # build: videoServerApp
    networks:
      - cat
    depends_on:
      - nfsserver
    env_file:
      - video.env
    privileged: true
    volumes:
      - "video:/video/"
        
  videoserver4:
    image: truongvanhuy2000/videoserverapp
    # build: videoServerApp
    networks:
      - cat
    depends_on:
      - nfsserver
    env_file:
      - video.env
    privileged: true
    volumes:
      - "video:/video/"

  webserver:
    image: truongvanhuy2000/webserverapp
    # build: webServerApp
    ports:
      - "8000:5000"
    restart: unless-stopped
    volumes:
      - .:/webServerApp/webServer
    env_file:
      - web.env
    networks:
      - cat
    depends_on:
      - nfsserver
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  nfsserver:
    image: truongvanhuy2000/nfsserver
    # build: nfsServer
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data/resources
    volumes:
      - video2:/data/resources
    networks:
      - cat

networks:
  cat:
    ipam:
      driver: default
      config: 
        - subnet: 172.22.3.0/24

volumes:
  video:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfsserver,nolock,soft,rw
      device: ":/data/resources"
  video2:
    driver: local