website:
  host: "0.0.0.0"
  port: 5000

loadbalancer:
  host: "videoserverapp"
  port: 6000
  transport:
    method: "HTTP"
    timeout: 5

database:
  type: "REDIS"
  host: "database"
  port: 6379

logging:
  level: "INFO"