videoserver:
  image: 127.0.0.1:3500/videoserverapp
  # build: videoServerApp
  networks:
    - cat
  environment:
    - TRANSPORT_METHOD=GRPC
    - RESOURCE_DIR=videoServer/resources/
    - USE_AI=False
  volumes:
    - type: volume
      source: nfsvolume
      target: /video
      volume:
        nocopy: true
  deploy:
    mode: replicated
    replicas: 1
    placement:
      constraints: [node.role == worker]
