# This is where our server will be hosted on
httpserver:
  host: "0.0.0.0"
  port: 6000

# This is the address that will lead you to Ai Server
loadbalancer:
  host: "aiserver"
  port: 7000
  transport:
    method: "HTTP"
    timeout: 5

# This lead to database
database:
  type: "REDIS"
  host: "database"
  port: 6379

logging:
  level: "INFO"

# This lead to rabbitmq
rabbitmq:
  host: "rabbitmq"